[package]
name = "rtfetch"
version = "0.2.0"
edition = "2021"
build = "./src/build.rs"

[build-dependencies]
toml = "0.5"
serde_derive = "1.0"
serde = "1.0.97"

[dependencies]
color-print = "0.3.2"
sysinfo = "0.23.11"